### ISSUE TITLE
Compiler for gdal dependencies

### ISSUE THREAD

**Issue by Jubeku** [claimed-framework/c3#13]
We need a specific Dockerfile when gdal is part of the dependencies. 
Following Dockerfile works:

`requirements_docker = '\n'.join(requirements_docker)
docker_file = f"""
FROM python:latest
RUN apt update && apt install -y libgdal-dev
RUN pip install ipython==8.6.0 nbformat==5.7.0
RUN pip install GDAL==3.5.2
{requirements_docker}
RUN mkdir -p /opt/app-root/src/
WORKDIR /opt/app-root/src/
ADD {additionl_files_local} /opt/app-root/src/
ADD {target_code} /opt/app-root/src/
RUN chmod -R 777 /opt/app-root/src/
CMD ["ipython", "/opt/app-root/src/{target_code}"]
"""
with open("Dockerfile", "w") as text_file:
    text_file.write(docker_file)
!cat Dockerfile`

Should we implement it in a way so that gdal is part of the imports it is automatically selected @blumenstiel @romeokienzler ?

**Comment by romeokienzler** [comment]
@Jubeku I'd suggested to have 

1. a default docker image (as is)
2. A sys env variable with the name of a default docker image
3. A c3 parameter to override defaults 1 and 2

**Comment by blumenstiel** [comment]
@Jubeku I moved all template codes to a specific directory on the `dev` branch (https://github.com/claimed-framework/c3/blob/dev/src/templates/dockerfile_template).

We could implement a `--dockerfile_template_path` parameter so that you can overwrite the dockerfile_template if needed?

**Comment by blumenstiel** [comment]
Added `--dockerfile_template_path` to `dev` branch.
