### ISSUE TITLE
Kubernetes job yaml files are overwritten

### ISSUE THREAD

**Issue by blumenstiel** [claimed-framework/c3#15]
If a user edits the job yaml file and reruns C3, the changes are overwritten.

Potential solutions:
- Ask user before overwriting.
- Save old file in another file called `...job.yaml.old`.

cc @romeokienzler

**Comment by blumenstiel** [comment]
Added in #35
@romeokienzler Currently, only Kubernetes job yamls are not overwritten. Do we expect modifications of the KubeFlow yaml or the CWL file?

**Comment by blumenstiel** [comment]
@romeokienzler What should be the expected behavior for KubeFlow yaml or the CWL component file?
Is it expect that users edit these files? If yes, I can add them to the checks.

**Comment by romeokienzler** [comment]
@blumenstiel no, they can be overwritten. Even (imho) the job yaml AS it is the users responsibility to create to copy

For the Jobs one can use kustomize to patch it. If we wanna be extraordinary user friendly we could generate the kustomization.yaml and overlay 

https://devopscube.com/kustomize-tutorial/

**Comment by blumenstiel** [comment]
I think that is a little bit too much, we are already renaming the yaml when it is modified to save the changes.

Closing this issue because it is implemented in the last C3 version.
