### ISSUE TITLE
return code 0 although error on docker push

### ISSUE THREAD

**Issue by romeokienzler** [claimed-framework/c3#17]
`INFO - Successfully built image
INFO - Pushing images to registry us.icr.io/geodn
unauthorized: Authorization required. See https://cloud.ibm.com/docs/Registry?topic=Registry-troubleshoot-auth-req
ERROR - Could not push images to namespace us.icr.io/geodn. Please check if docker is logged in or select a namespace with access.
INFO - Write KubeFlow component yaml to cgw-hls-for-agb-inference.yaml
INFO - Write kubernetes job yaml to cgw-hls-for-agb-inference.job.yaml
INFO - Remove local files
(.venv) romeokienzler:operators$ echo $?
0`

**Comment by blumenstiel** [comment]
Added raise error. Added `--test_mode` for testing without pushing the image.

**Comment by blumenstiel** [comment]
Added in pr #21
