### ISSUE TITLE
invalid reference format: repository name must be lowercase

### ISSUE THREAD

**Issue by romeokienzler** [claimed-framework/c3#24]
When the python file has uppercase letters the generated container name has as well which breaks docker

'invalid argument "claimed-AGB-model-card-exp-Swin-unfrozen-encoder-321-br:0.1" for "-t, --tag" flag: invalid reference format: repository name must be lowercase'

`INFO - Operator name: AGB-model-card-exp-Swin-unfrozen-encoder-321-br
INFO - Description:: "TODO: Update the description of the operator in the first doc string. This is the operator description. The file name becomes the operator name. – CLAIMED V0.1"
INFO - Inputs: {'log_level': {'description': 'update log level', 'type': 'String', 'default': 'INFO'}, 'NUM_FRAMES': {'description': 'model_bands = [2, 3, 4, 8, 11, 12]', 'type': 'Integer', 'default': '1'}, 'IMG_SIZE': {'description': '', 'type': 'Integer', 'default': '224'}, 'DATA_LOADER_NUM_WORKERS': {'description': '', 'type': 'Integer', 'default': '8'}, 'NUM_LAYERS': {'description': 'model related', 'type': 'Integer', 'default': '12'}, 'PATCH_SIZE': {'description': '', 'type': 'Integer', 'default': '16'}, 'EMBED_DIM': {'description': '', 'type': 'Integer', 'default': '768'}, 'NUM_HEADS': {'description': '', 'type': 'Integer', 'default': '12'}, 'CHECKPOINT_PATH': {'description': '', 'type': 'String', 'default': ''}}
INFO - Outputs: {}
INFO - Requirements: []
INFO - Selected additional files: []
INFO - Create Dockerfile
WARNING - The current implementation can only query local docker images. Please use an argument '-v <version>' to avoid duplicates.
INFO - Using default version 0.1. No prior image tag found for docker.io/dummy/claimed-AGB-model-card-exp-Swin-unfrozen-encoder-321-br.
INFO - Building container image claimed-AGB-model-card-exp-Swin-unfrozen-encoder-321-br:0.1
invalid argument "claimed-AGB-model-card-exp-Swin-unfrozen-encoder-321-br:0.1" for "-t, --tag" flag: invalid reference format: repository name must be lowercase
See 'docker build --help'.
Traceback (most recent call last):
  File "/Users/mmu/Documents/IBM_projects/AIFloodDetection/AGB_GHG_project/code/AGB_GHG/mmsegmentation/configs/agb/./.venv/bin/c3_create_operator", line 8, in <module>
    sys.exit(main())
  File "/Users/mmu/Documents/IBM_projects/AIFloodDetection/AGB_GHG_project/code/AGB_GHG/mmsegmentation/configs/agb/.venv/lib/python3.9/site-packages/c3/create_operator.py", line 247, in main
    create_operator(
  File "/Users/mmu/Documents/IBM_projects/AIFloodDetection/AGB_GHG_project/code/AGB_GHG/mmsegmentation/configs/agb/.venv/lib/python3.9/site-packages/c3/create_operator.py", line 105, in create_operator
    subprocess.run(
  File "/Users/mmu/Conda/anaconda3/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'build', '--platform', 'linux/amd64', '-t', 'claimed-AGB-model-card-exp-Swin-unfrozen-encoder-321-br:0.1', '.']' returned non-zero exit status 125.`

**Comment by blumenstiel** [comment]
@romeokienzler I fixed this issue in the last release. Can you test again if it is working?

**Comment by romeokienzler** [comment]
Thanks @blumenstiel I confirm it works
