### ISSUE TITLE
compile to cwl tasks doesn't create int type

### ISSUE THREAD

**Issue by romeokienzler** [claimed-framework/c3#25]
Using  claimed-c3==0.2.15

The following call:

`c3_create_operator --test_mode -r us.ico.io/geodn operator_example.py `

produces from:

`num_values = int(os.getenv('num_values', 5))`

this cwl task parameter definition:

>   num_values:
>     type: string
>     default: "5"
>     inputBinding:
>       position: 5
>       prefix: --num_values

Expected:

` type: int`

**Comment by blumenstiel** [comment]
Fixed in #39
