### ISSUE TITLE
enable pip install -r requirements.txt

### ISSUE THREAD

**Issue by romeokienzler** [claimed-framework/c3#27]
when adding the dependency hint in the python form:

`#pip install -r requirements.txt`

C3 doesn't find the file, also when passing it as additional file, the position is wrong in the Docker template, it gets added after the pip install command runs, but even if the template is changed the file is not found, but when passing the correct path like:

`#pip install -r /app/scr/requirements.txt`

Then the resulting Dockerfile only contains:

RUN pip install

**Comment by blumenstiel** [comment]
@romeokienzler It should work with `pip install -r /opt/app-root/src/requirements.txt`.

Maybe, we could replace `-r ` with `-r /opt/app-root/src/` if the working dir is not included?

**Comment by romeokienzler** [comment]
Just tested with:

# pip install -r ~/requirements.txt

And it worked for the UBI case - so a replacement with ~/ should work for all types of images

**Comment by blumenstiel** [comment]
Implemented it with
```
    # Add missing home directory to the command `pip install -r ~/requirements.txt` 
    requirements = [r if '~/' in r else r.replace('-r ', '-r ~/') for r in requirements]
```

**Comment by blumenstiel** [comment]
Added in #35
