### ISSUE TITLE
output of docker build not visible during c3_create_component

### ISSUE THREAD

**Issue by romeokienzler** [claimed-framework/c3#30]
while the c3_create_component command runs, the output of the docker build command is not visible

**Comment by blumenstiel** [comment]
@romeokienzler The output should be visible when `--log_level DEBUG` is set.
I don't show the logs to provide a better overview to the user. I can add a message to propose the DEBUG mode if the build fails.

**Comment by romeokienzler** [comment]
Oh, great...didn't know that this level controls the build process, but now it is totally clear, thank you and yes, such a message would be helpful to new users

**Comment by romeokienzler** [comment]
@blumenstiel

**Comment by blumenstiel** [comment]
I added an explanation in GettingStarted.md.

"If you want to display the docker logs, you can add `--log_level DEBUG`."
