### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'groups', v0.3.6

### ISSUE THREAD

**Issue by romeokienzler** [claimed-framework/c3#57]
To reproduce: 

git clone git@github.ibm.com:GeoDN-Discovery/openeo-geodn-driver.git

1. cd open openeo-geodn-driver

2. add the following two lines to the 1st code cell in GeoDN-HLSS30-demo.ipynb:
```
!pip install elyra
!pip install -r dev_requirements.txt
```

3. c3_create_operator examples/demos/GeoDN-HLSS30-demo.ipynb dev_requirements.txt

> (.venv) romeokienzler:openeo-geodn-driver$ c3_create_operator examples/demos/GeoDN-HLSS30-demo.ipynb dev_requirements.txt 
> INFO - Parameters: 
> INFO - file_path: examples/demos/GeoDN-HLSS30-demo.ipynb
> INFO - repository: None
> INFO - version: None
> INFO - additional_files: dev_requirements.txt
> /home/romeokienzler/gitco/openeo-geodn-driver/.venv/lib64/python3.12/site-packages/nbformat/__init__.py:96: MissingIDFieldWarning: Cell is missing an id field, this will become a hard error in future nbformat versions. You may want to use `normalize()` on your notebooks before validations (available since nbformat 5.1.4). Previous versions of nbformat are fixing this issue transparently, and will stop doing so in the future.
>   validate(nb)
> INFO - Operator name: geodn-hlss30-demo
> INFO - Description: "# GeoDN.Discovery: Exploring HLSS30 using integration between GeoDN OpenEO and GeoDN STAC services  – CLAIMED V0.1"
> INFO - Inputs:
> log_level: {'description': 'update log level', 'type': 'String', 'default': 'INFO'}
> INFO - Outputs:
> USE_PYGEOS: {'description': 'Output path for USE_PYGEOS', 'type': 'String'}
> OPENEO_USERNAME: {'description': 'Output path for OPENEO_USERNAME', 'type': 'String'}
> OPENEO_PASSWORD: {'description': 'Output path for OPENEO_PASSWORD', 'type': 'String'}
> INFO - Requirements: pip install elyra; pip install -r dev_requirements.txt
> INFO - Found 1 additional files and directories
> dev_requirements.txt
> Traceback (most recent call last):
>   File "/home/romeokienzler/gitco/openeo-geodn-driver/.venv/bin/c3_create_operator", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/home/romeokienzler/gitco/openeo-geodn-driver/.venv/lib64/python3.12/site-packages/c3/create_operator.py", line 485, in main
>     create_operator(
>   File "/home/romeokienzler/gitco/openeo-geodn-driver/.venv/lib64/python3.12/site-packages/c3/create_operator.py", line 348, in create_operator
>     create_dockerfile(dockerfile_template, requirements, target_code, target_dir, additional_files_found, working_dir,
>   File "/home/romeokienzler/gitco/openeo-geodn-driver/.venv/lib64/python3.12/site-packages/c3/create_operator.py", line 30, in create_dockerfile
>     if len(r_file_search.groups()):
>            ^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by blumenstiel** [comment]
Fixed in #58
