### ISSUE TITLE
Allow to include multiple additional files when generating components

### ISSUE THREAD

**Issue by Jubeku** [claimed-framework/c3#8]
When compiling a component using `generate_kfp_component.ipynb`, allow to include multiple files to be added to the docker container. 
Usage:
`ipython generate_kfp_component.ipynb notebook_path=<yourcomponent> version=$version additionl_files=[file1,file2]`

**Comment by blumenstiel** [comment]
My idea is that c3 takes the first positional argument as the component name and all following arguments as additional files (including wildcards). Together with a cli tool it would look like this:
```
claimed create operator -v "X.X" -r "docker.io/namespace" "component.py" "additional_file1.py" "file2.py"
```

@Jubeku What do you think of it?

**Comment by Jubeku** [comment]
@blumenstiel sounds good! My workaround solution was merged here: https://github.com/claimed-framework/c3/pull/9

**Comment by blumenstiel** [comment]
Implemented in dev branch
